In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [7]:
application_train =  pd.read_csv('../data/application_train.csv')
X = application_train.drop("TARGET", axis= 1)
y = application_train["TARGET"]

# chia làm 2 lần
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, 
    test_size=0.3, 
    random_state=42, 
    stratify=y) 

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size= 0.5,
    random_state=42,
    stratify=y_temp
)

In [9]:
validation = X_val.copy()
validation.insert(1, "TARGET", y_val)

test = X_test.copy()
test.insert(1,"TARGET", y_test)

In [10]:
validation

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
37319,143234,1,Cash loans,M,Y,Y,1,202500.0,1042560.0,40572.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
273724,417276,0,Cash loans,M,N,Y,1,202500.0,582723.0,69156.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
261810,403066,0,Cash loans,F,N,N,1,135000.0,245619.0,11812.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
188533,318583,0,Cash loans,M,Y,Y,1,225000.0,1354500.0,35860.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
16097,118775,0,Cash loans,F,N,N,0,126000.0,639963.0,21280.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275856,419646,0,Cash loans,F,Y,Y,0,46350.0,171000.0,11898.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
266994,409341,0,Cash loans,F,N,N,0,135000.0,675000.0,34596.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
162005,287811,1,Revolving loans,M,Y,Y,0,270000.0,585000.0,29250.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
219180,353909,0,Cash loans,M,N,N,0,238500.0,420894.0,22963.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
170875,298028,0,Cash loans,M,Y,Y,0,135000.0,283500.0,15507.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0

In [11]:
test

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
17424,120321,0,Cash loans,F,N,N,1,135000.0,269550.0,16416.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
305296,453712,1,Cash loans,F,Y,Y,1,157500.0,1546020.0,42642.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
17224,120090,0,Cash loans,F,N,Y,0,112500.0,364896.0,23449.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
215169,349328,0,Cash loans,F,N,N,0,99000.0,508495.5,21672.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
181299,310116,0,Revolving loans,F,N,N,0,67500.0,202500.0,10125.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8926,110387,0,Cash loans,F,Y,Y,3,202500.0,1354500.0,56029.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
98680,214580,0,Revolving loans,F,N,N,0,292500.0,495000.0,24750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
57290,166401,0,Cash loans,F,Y,N,0,135000.0,417024.0,25200.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
257190,397624,0,Cash loans,F,N,N,0,67500.0,292500.0,13684.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
303795,451981,0,Cash loans,M,Y,Y,1,270000.0,1436850.0,42142.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0

## train: profile of borrower borrow at this time

In [12]:
train = X_train.copy()
train.insert(1, "TARGET", y_train)

train

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
159703,285133,0,Cash loans,F,Y,Y,2,405000.0,1971072.0,68643.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
79269,191894,0,Cash loans,M,N,Y,0,337500.0,508495.5,38146.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
232615,369428,0,Cash loans,M,N,Y,1,112500.0,110146.5,13068.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
33420,138717,0,Cash loans,F,N,Y,2,40500.0,66384.0,3519.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
88191,202381,0,Cash loans,M,Y,N,0,225000.0,298512.0,31801.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170183,297241,0,Cash loans,F,N,Y,1,157500.0,846517.5,33700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
31304,136325,0,Revolving loans,F,N,Y,1,135000.0,405000.0,20250.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
121193,240509,0,Cash loans,F,N,N,0,157500.0,272520.0,21528.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
248504,387513,0,Cash loans,F,N,N,0,90000.0,246357.0,24493.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
301908,449767,1,Revolving loans,M,Y,Y,1,225000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0

In [25]:
sk_id_curr_train = train["SK_ID_CURR"]
sk_id_curr_val = validation["SK_ID_CURR"]
sk_id_curr_test = test["SK_ID_CURR"]

In [5]:
train.describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
count,307511.000000,307511.000000,307511.000000,3.075110e+05,3.075110e+05,307499.000000,3.072330e+05,307511.000000,307511.000000,307511.000000,...,307511.000000,307511.000000,307511.000000,307511.000000,265992.000000,265992.000000,265992.000000,265992.000000,265992.000000,265992.000000
mean,278180.518577,0.080729,0.417052,1.687979e+05,5.990260e+05,27108.573909,5.383962e+05,0.020868,-16036.995067,63815.045904,...,0.008130,0.000595,0.000507,0.000335,0.006402,0.007000,0.034362,0.267395,0.265474,1.899974
std,102790.175348,0.272419,0.722121,2.371231e+05,4.024908e+05,14493.737315,3.694465e+05,0.013831,4363.988632,141275.766519,...,0.089798,0.024387,0.022518,0.018299,0.083849,0.110757,0.204685,0.916002,0.794056,1.869295
min,100002.000000,0.000000,0.000000,2.565000e+04,4.500000e+04,1615.500000,4.050000e+04,0.000290,-25229.000000,-17912.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,189145.500000,0.000000,0.000000,1.125000e+05,2.700000e+05,16524.000000,2.385000e+05,0.010006,-19682.000000,-2760.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,278202.000000,0.000000,0.000000,1.471500e+05,5.135310e+05,24903.000000,4.500000e+05,0.018850,-15750.000000,-1213.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,367142.500000,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,0.028663,-12413.000000,-289.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
max,456255.000000,1.000000,19.000000,1.170000e+08,4.050000e+06,258025.500000,4.050000e+06,0.072508,-7489.000000,365243.000000,...,1.000000,1.000000,1.000000,1.000000,4.000000,9.000000,8.000000,27.000000,261.000000,25.000000

In [6]:
train.isnull().mean()

SK_ID_CURR                    0.000000
TARGET                        0.000000
NAME_CONTRACT_TYPE            0.000000
CODE_GENDER                   0.000000
FLAG_OWN_CAR                  0.000000
                                ...
AMT_REQ_CREDIT_BUREAU_DAY     0.135016
AMT_REQ_CREDIT_BUREAU_WEEK    0.135016
AMT_REQ_CREDIT_BUREAU_MON     0.135016
AMT_REQ_CREDIT_BUREAU_QRT     0.135016
AMT_REQ_CREDIT_BUREAU_YEAR    0.135016
Length: 122, dtype: float64

In [7]:
train['TARGET'].value_counts(normalize=True)

TARGET
0    0.919271
1    0.080729
Name: proportion, dtype: float64

In [ ]:
def bad_rate_table_categorical(df, col, target='TARGET'):

    result = []


    table = (
            df.groupby(col)[target]
              .agg(Total='count', Bad='sum')
              .reset_index()
        )

    table['Good'] = table['Total'] - table['Bad']
    table['Bad Rate'] = (table['Bad'] / table['Total'] * 100).round(2)
    table["Population %"] = ((table['Total'] / table['Total'].sum())*100).round(2)
    table = table.rename(columns={col: 'Category'})

    result.append(table)

    return pd.concat(result, ignore_index=True)

In [ ]:
def bad_rate_table_numeric(df, col, target='TARGET', q = 5):
    temp = df[[col,target]].copy()
    temp['bins'] = pd.qcut(temp[col], q = q, duplicates='drop')
    
    table = (temp.groupby('bins', observed = False)[target].agg(
        Total = 'count',
        Bad = 'sum'
    ).reset_index())
    table['Population %'] = (table['Total'] / table['Total'].sum() * 100).round(2)
    table['Bad Rate'] = (table['Bad'] / table['Total'] * 100).round(2)

    return table[['Bin', 'Population %', 'Bad Rate']]

In [21]:
def train_application_features(df):

    app = df.copy()

    # =====================================================
    # Employment placeholder
    # 365243 = placeholder value
    # =====================================================
    app["EMPLOYED_PLACEHOLDER_FLAG"] = (
        app["DAYS_EMPLOYED"] == 365243
    ).astype(int)

    app.loc[
        app["DAYS_EMPLOYED"] == 365243,
        "DAYS_EMPLOYED"
    ] = np.nan

    # =====================================================
    # Income & Debt Capacity
    # =====================================================
    app["annuity_income_ratio"] = np.where(
        app["AMT_INCOME_TOTAL"] > 0,
        app["AMT_ANNUITY"] / app["AMT_INCOME_TOTAL"],
        np.nan
    )

    app["credit_income_ratio"] = np.where(
        app["AMT_INCOME_TOTAL"] > 0,
        app["AMT_CREDIT"] / app["AMT_INCOME_TOTAL"],
        np.nan
    )

    app["credit_goods_ratio"] = np.where(
        app["AMT_GOODS_PRICE"] > 0,
        app["AMT_CREDIT"] / app["AMT_GOODS_PRICE"],
        np.nan
    )

    app["income_per_family"] = np.where(
        app["CNT_FAM_MEMBERS"] > 0,
        app["AMT_INCOME_TOTAL"] / app["CNT_FAM_MEMBERS"],
        np.nan
    )

    # =====================================================
    # Age & Employment
    # =====================================================
    app["age_years"] = (
        -app["DAYS_BIRTH"] / 365
    )

    app["employment_years"] = (
        -app["DAYS_EMPLOYED"] / 365
    )

    app["employment_age_ratio"] = np.where(
        app["DAYS_BIRTH"] < 0,
        app["DAYS_EMPLOYED"] / app["DAYS_BIRTH"],
        np.nan
    )

    # =====================================================
    # External Scores
    # =====================================================
    ext_cols = [
        "EXT_SOURCE_1",
        "EXT_SOURCE_2",
        "EXT_SOURCE_3"
    ]

    app["ext_mean"] = app[ext_cols].mean(axis=1)

    app["ext_min"] = app[ext_cols].min(axis=1)

    app["ext_max"] = app[ext_cols].max(axis=1)

    app["ext_std"] = app[ext_cols].std(axis=1)

    app["ext_missing_count"] = (
        app[ext_cols]
        .isna()
        .sum(axis=1)
    )

    return app

In [22]:
train_feature = train_application_features(train)

validation_feature = train_application_features(validation)
test_feature = train_application_features(test)

In [23]:
train_feature

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,credit_goods_ratio,income_per_family,age_years,employment_years,employment_age_ratio,ext_mean,ext_min,ext_max,ext_std,ext_missing_count
159703,285133,0,Cash loans,F,Y,Y,2,405000.0,1971072.0,68643.0,...,1.095040,101250.0,37.224658,2.816438,0.075661,0.548664,0.327724,0.675243,0.192016,0
79269,191894,0,Cash loans,M,N,Y,0,337500.0,508495.5,38146.5,...,1.118802,168750.0,48.063014,3.309589,0.068859,0.528944,0.440058,0.617831,0.125704,1
232615,369428,0,Cash loans,M,N,Y,1,112500.0,110146.5,13068.0,...,1.223850,37500.0,31.663014,1.624658,0.051311,0.502890,0.358038,0.647742,0.204852,1
33420,138717,0,Cash loans,F,N,Y,2,40500.0,66384.0,3519.0,...,1.475200,10125.0,43.150685,14.728767,0.341333,0.478780,0.385576,0.601801,0.111154,0
88191,202381,0,Cash loans,M,Y,N,0,225000.0,298512.0,31801.5,...,1.105600,112500.0,54.553425,3.273973,0.060014,0.704591,0.656651,0.737632,0.042497,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170183,297241,0,Cash loans,F,N,Y,1,157500.0,846517.5,33700.5,...,1.237599,52500.0,40.389041,21.367123,0.529033,0.689566,0.668457,0.710674,0.029852,1
31304,136325,0,Revolving loans,F,N,Y,1,135000.0,405000.0,20250.0,...,1.000000,45000.0,42.120548,1.630137,0.038702,0.549668,0.549668,0.549668,NaN,2
121193,240509,0,Cash loans,F,N,N,0,157500.0,272520.0,21528.0,...,1.211200,157500.0,52.150685,11.873973,0.227686,0.585180,0.569702,0.600658,0.021889,1
248504,387513,0,Cash loans,F,N,N,0,90000.0,246357.0,24493.5,...,1.052808,45000.0,63.254795,NaN,NaN,0.572617,0.461966,0.683269,0.156485,1
301908,449767,1,Revolving loans,M,Y,Y,1,225000.0,270000.0,13500.0,...,1.000000,75000.0,47.775342,21.443836,0.448847,0.309678,0.003234,0.616122,0.433377,1

## Bureau và Bureau_balance

In [27]:
#bureau: mỗi dòng là 1 khoản vay của khách hàng tại một tổ chức tín dụng khác Home Credit
bureau_train = pd.read_csv("../data/bureau.csv")
bureau = bureau_train[bureau_train["SK_ID_CURR"].isin(sk_id_curr_train)]

bureau_val = bureau_train[bureau_train["SK_ID_CURR"].isin(sk_id_curr_val)]
bureau_test = bureau_train[bureau_train["SK_ID_CURR"].isin(sk_id_curr_test)]


sk_id_bureau_train = bureau["SK_ID_BUREAU"]
sk_id_bureau_val = bureau_val["SK_ID_BUREAU"]
sk_id_bureau_test = bureau_test["SK_ID_BUREAU"]



bureau

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.00,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.00,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.50,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.00,NaN,NaN,0.0,Consumer credit,-21,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716421,375755,5057734,Closed,currency 1,-1335,0,-1152.0,-1152.0,NaN,0,195408.00,0.0,NaN,0.0,Consumer credit,-1139,NaN
1716422,375755,5057742,Closed,currency 1,-2648,0,31129.0,-189.0,NaN,0,202500.00,0.0,NaN,0.0,Credit card,-109,NaN
1716423,259355,5057750,Active,currency 1,-44,0,-30.0,NaN,0.0,0,11250.00,11250.0,0.0,0.0,Microloan,-19,NaN
1716424,100044,5057754,Closed,currency 1,-2648,0,-2433.0,-2493.0,5476.5,0,38130.84,0.0,0.0,0.0,Consumer credit,-2493,NaN
1716425,100044,5057762,Closed,currency 1,-1809,0,-1628.0,-970.0,NaN,0,15570.00,NaN,NaN,0.0,Consumer credit,-967,NaN

In [16]:
bureau["SK_ID_CURR"].nunique()

184421

In [8]:
bureau[["DAYS_CREDIT","DAYS_ENDDATE_FACT","DAYS_CREDIT_UPDATE"]] = -1* bureau[["DAYS_CREDIT","DAYS_ENDDATE_FACT","DAYS_CREDIT_UPDATE"]]
bureau.head()

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,497,0,-153.0,153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,131,NaN
1,215354,5714463,Active,currency 1,208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,20,NaN
2,215354,5714464,Active,currency 1,203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,16,NaN
3,215354,5714465,Active,currency 1,203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,16,NaN
4,215354,5714466,Active,currency 1,629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,21,NaN

In [9]:
bureau.describe()

,SK_ID_CURR,SK_ID_BUREAU,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
count,1.716428e+06,1.716428e+06,1.716428e+06,1.716428e+06,1.610875e+06,1.082775e+06,5.919400e+05,1.716428e+06,1.716415e+06,1.458759e+06,1.124648e+06,1.716428e+06,1.716428e+06,4.896370e+05
mean,2.782149e+05,5.924434e+06,1.142108e+03,8.181666e-01,5.105174e+02,1.017437e+03,3.825418e+03,6.410406e-03,3.549946e+05,1.370851e+05,6.229515e+03,3.791276e+01,5.937483e+02,1.571276e+04
std,1.029386e+05,5.322657e+05,7.951649e+02,3.654443e+01,4.994220e+03,7.140106e+02,2.060316e+05,9.622391e-02,1.149811e+06,6.774011e+05,4.503203e+04,5.937650e+03,7.207473e+02,3.258269e+05
min,1.000010e+05,5.000000e+06,0.000000e+00,0.000000e+00,-4.206000e+04,-0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-4.705600e+06,-5.864061e+05,0.000000e+00,-3.720000e+02,0.000000e+00
25%,1.888668e+05,5.463954e+06,4.740000e+02,0.000000e+00,-1.138000e+03,4.250000e+02,0.000000e+00,0.000000e+00,5.130000e+04,0.000000e+00,0.000000e+00,0.000000e+00,3.300000e+01,0.000000e+00
50%,2.780550e+05,5.926304e+06,9.870000e+02,0.000000e+00,-3.300000e+02,8.970000e+02,0.000000e+00,0.000000e+00,1.255185e+05,0.000000e+00,0.000000e+00,0.000000e+00,3.950000e+02,0.000000e+00
75%,3.674260e+05,6.385681e+06,1.666000e+03,0.000000e+00,4.740000e+02,1.489000e+03,0.000000e+00,0.000000e+00,3.150000e+05,4.015350e+04,0.000000e+00,0.000000e+00,9.080000e+02,1.350000e+04
max,4.562550e+05,6.843457e+06,2.922000e+03,2.792000e+03,3.119900e+04,4.202300e+04,1.159872e+08,9.000000e+00,5.850000e+08,1.701000e+08,4.705600e+06,3.756681e+06,4.194700e+04,1.184534e+08

In [10]:
bureau.isnull().mean()

SK_ID_CURR                0.000000
SK_ID_BUREAU              0.000000
CREDIT_ACTIVE             0.000000
CREDIT_CURRENCY           0.000000
DAYS_CREDIT               0.000000
CREDIT_DAY_OVERDUE        0.000000
DAYS_CREDIT_ENDDATE       0.061496
DAYS_ENDDATE_FACT         0.369170
AMT_CREDIT_MAX_OVERDUE    0.655133
CNT_CREDIT_PROLONG        0.000000
AMT_CREDIT_SUM            0.000008
AMT_CREDIT_SUM_DEBT       0.150119
AMT_CREDIT_SUM_LIMIT      0.344774
AMT_CREDIT_SUM_OVERDUE    0.000000
CREDIT_TYPE               0.000000
DAYS_CREDIT_UPDATE        0.000000
AMT_ANNUITY               0.714735
dtype: float64

In [29]:
bureau_bal_train = pd.read_csv("../data/bureau_balance.csv")

bureau_bal = bureau_bal_train[bureau_bal_train["SK_ID_BUREAU"].isin(sk_id_bureau_train)]
bureau_bal_val = bureau_bal_train[bureau_bal_train["SK_ID_BUREAU"].isin(sk_id_bureau_val)]
bureau_bal_test = bureau_bal_train[bureau_bal_train["SK_ID_BUREAU"].isin(sk_id_bureau_test)]

bureau_bal.head()

     SK_ID_BUREAU  MONTHS_BALANCE STATUS
306       5715478               0      C
307       5715478              -1      C
308       5715478              -2      C
309       5715478              -3      C
310       5715478              -4      C

In [31]:
"""
bb = bureau_bal.copy()
status_map = {
    'X': 0,
    'C': 0,
    '0': 0,
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5
}

bb["DPD"] = bb["STATUS"].map(status_map).astype(int)

# Flag bad month
bb["BAD_MONTH"] = (bb["DPD"] > 0).astype(int)

bb["DPD30"] = (bb["DPD"] >= 2).astype(int)
bb["DPD60"] = (bb["DPD"] >= 3).astype(int)
bb["DPD90"] = (bb["DPD"] >= 4).astype(int)

# Khoản vay đang active
bb["ACTIVE_MONTH"] = (~bb["STATUS"].isin(["C", "X"])).astype(int)
"""


def process_bureau_balance(df, status_map=None):
    if status_map is None:
        status_map = {
            'X': 0, 'C': 0, '0': 0,
            '1': 1, '2': 2, '3': 3, '4': 4, '5': 5
        }
    
    df_processed = df.copy()
    
    # Map STATUS sang DPD
    df_processed["DPD"] = df_processed["STATUS"].map(status_map).fillna(-1).astype(int)
    
    # Flag bad month
    df_processed["BAD_MONTH"] = (df_processed["DPD"] > 0).astype(int)
    
    # DPD categories
    df_processed["DPD30"] = (df_processed["DPD"] >= 2).astype(int)
    df_processed["DPD60"] = (df_processed["DPD"] >= 3).astype(int)
    df_processed["DPD90"] = (df_processed["DPD"] >= 4).astype(int)
    
    # Active flag
    df_processed["ACTIVE_MONTH"] = (~df_processed["STATUS"].isin(["C", "X"])).astype(int)
    
    return df_processed


def bureau_balance_window_feat(df, window):
    temp = df[df['MONTHS_BALANCE'] >= (-window +1)].copy()
    
    feature = (
        temp.groupby("SK_ID_BUREAU")
            .agg(
                max_dpd=("DPD", "max"),

                bad_months=("BAD_MONTH", "sum"),

                months_observed=("MONTHS_BALANCE", "count"),

                months_active=("ACTIVE_MONTH", "sum"),

                dpd30_months=("DPD30", "sum"),

                dpd60_months=("DPD60", "sum"),

                dpd90_months=("DPD90", "sum")
            )
            .reset_index()
    )
    
    #ratio of bad month
    feature['bad_ratio'] = feature['bad_months'] / feature['months_observed']
    
    feature = feature.rename(columns={
        "max_dpd": f"max_dpd_{window}m",
        "bad_months": f"bad_months_{window}m",
        "months_observed": f"months_observed_{window}m",
        "months_active": f"months_active_{window}m",
        "dpd30_months": f"dpd30_months_{window}m",
        "dpd60_months": f"dpd60_months_{window}m",
        "dpd90_months": f"dpd90_months_{window}m",
        "bad_ratio": f"bad_ratio_{window}m"
    })

    
    return feature

In [32]:
bb = process_bureau_balance(bureau_bal)
bb_val = process_bureau_balance(bureau_bal_val)
bb_test = process_bureau_balance(bureau_bal_test)

bb6 = bureau_balance_window_feat(bb, 6)
bb6_val = bureau_balance_window_feat(bb_val,6)
bb6_test = bureau_balance_window_feat(bb_test,6)


bb12 = bureau_balance_window_feat(bb, 12)
bb12_val = bureau_balance_window_feat(bb_val,12)
bb12_test = bureau_balance_window_feat(bb_test,12)


bb24 = bureau_balance_window_feat(bb, 24)
bb24_val = bureau_balance_window_feat(bb_val, 24)
bb24_test = bureau_balance_window_feat(bb_test, 24)

In [34]:
bureau_balance_feature = (
    bb6
    .merge(bb12, on="SK_ID_BUREAU", how="outer")
    .merge(bb24, on="SK_ID_BUREAU", how="outer")
)

bureau_balance_feature_val = (
    bb6_val
    .merge(bb12_val, on="SK_ID_BUREAU", how="outer")
    .merge(bb24_val, on="SK_ID_BUREAU", how="outer")
)

bureau_balance_feature_test = (
    bb6_test
    .merge(bb12_test, on="SK_ID_BUREAU", how="outer")
    .merge(bb24_test, on="SK_ID_BUREAU", how="outer")
)


bureau_balance_feature.head()

,SK_ID_BUREAU,max_dpd_6m,bad_months_6m,months_observed_6m,months_active_6m,dpd30_months_6m,dpd60_months_6m,dpd90_months_6m,bad_ratio_6m,max_dpd_12m,...,dpd90_months_12m,bad_ratio_12m,max_dpd_24m,bad_months_24m,months_observed_24m,months_active_24m,dpd30_months_24m,dpd60_months_24m,dpd90_months_24m,bad_ratio_24m
0,5008804,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1,1,16,2,0,0,0,0.062500
1,5008805,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1,1,15,2,0,0,0,0.066667
2,5008808,0.0,0.0,5.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,5,2,0,0,0,0.000000
3,5008809,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0,2,0,0,0,0,0.000000
4,5008810,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,24,5,0,0,0,0.000000

In [35]:
bureau_enriched = bureau.merge(
    bureau_balance_feature,
    on="SK_ID_BUREAU",
    how="left"
)


bureau_enriched_val = bureau_val.merge(
    bureau_balance_feature_val,
    on="SK_ID_BUREAU",
    how="left"
)
 
bureau_enriched_test = bureau_test.merge(
    bureau_balance_feature_test,
    on="SK_ID_BUREAU",
    how="left"
)


bureau_enriched.head()

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,...,dpd90_months_12m,bad_ratio_12m,max_dpd_24m,bad_months_24m,months_observed_24m,months_active_24m,dpd30_months_24m,dpd60_months_24m,dpd90_months_24m,bad_ratio_24m
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
bureau_enriched_test

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,...,dpd90_months_12m,bad_ratio_12m,max_dpd_24m,bad_months_24m,months_observed_24m,months_active_24m,dpd30_months_24m,dpd60_months_24m,dpd90_months_24m,bad_ratio_24m
0,400486,5714504,Closed,currency 1,-2413,0,-1864.0,-2128.0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,400486,5714506,Active,currency 1,-941,0,-17.0,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,400486,5714507,Closed,currency 1,-1110,0,-745.0,-727.0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,400486,5714508,Closed,currency 1,-2133,0,-1038.0,-1127.0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,400486,5714509,Active,currency 1,-391,0,705.0,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219557,181001,5057533,Closed,currency 1,-911,0,-634.0,-634.0,0.000,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219558,288038,5057657,Active,currency 1,-541,0,7.0,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219559,288038,5057665,Closed,currency 1,-463,0,-36.0,-36.0,6863.715,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219560,246829,5057770,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219561,246829,5057778,Closed,currency 1,-463,0,NaN,-387.0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
# =====================================
# Aggregate toàn bộ lịch sử theo SK_ID_BUREAU
# =====================================
"""
bb_all = (
    bb.groupby("SK_ID_BUREAU")
      .agg(
          max_dpd_all=("DPD", "max"),
          bad_months_all=("BAD_MONTH", "sum"),
          months_observed_all=("MONTHS_BALANCE", "count"),
          months_active_all=("ACTIVE_MONTH", "sum"),
          dpd30_months_all=("DPD30", "sum"),
          dpd60_months_all=("DPD60", "sum"),
          dpd90_months_all=("DPD90", "sum")
      )
      .reset_index()
)


# Tỷ lệ tháng quá hạn trên toàn bộ lịch sử
bb_all["bad_ratio_all"] = (
    bb_all["bad_months_all"] /
    bb_all["months_observed_all"]
).round(4)

bureau_enriched_new = bureau_enriched.merge(
    bb_all,
    on="SK_ID_BUREAU",
    how="left"
)
bureau_enriched_new.head()
"""



def merge_bureau_balance_features(bureau_enriched, bb):
    bb_all = (
        bb.groupby("SK_ID_BUREAU")
          .agg(
              max_dpd_all=("DPD", "max"),
              bad_months_all=("BAD_MONTH", "sum"),
              months_observed_all=("MONTHS_BALANCE", "count"),
              months_active_all=("ACTIVE_MONTH", "sum"),
              dpd30_months_all=("DPD30", "sum"),
              dpd60_months_all=("DPD60", "sum"),
              dpd90_months_all=("DPD90", "sum")
          )
          .reset_index()
    )
    
    bb_all["bad_ratio_all"] = (bb_all["bad_months_all"] / bb_all["months_observed_all"]).round(4)
    
    return bureau_enriched.merge(bb_all, on="SK_ID_BUREAU", how="left")

bureau_enriched_new = merge_bureau_balance_features(bureau_enriched, bb)
bureau_enriched_new_val = merge_bureau_balance_features(bureau_enriched_val, bb_val)
bureau_enriched_new_test = merge_bureau_balance_features(bureau_enriched_test, bb_test)

In [40]:
def bureau_features(df):

    temp = df.copy()

    temp["ACTIVE_LOAN"] = (temp["CREDIT_ACTIVE"] == "Active").astype(int)

    temp["CLOSED_LOAN"] = (temp["CREDIT_ACTIVE"] == "Closed").astype(int)

    temp["OVERDUE_LOAN"] = (temp["AMT_CREDIT_SUM_OVERDUE"] > 0).astype(int)

    temp["DPD30_6M_LOAN"] = (temp["max_dpd_6m"] >= 2).astype(int)

    temp["DPD30_12M_LOAN"] = (temp["max_dpd_12m"] >= 2).astype(int)

    temp["DPD30_24M_LOAN"] = (temp["max_dpd_24m"] >= 2).astype(int)

    feature = (
        temp.groupby("SK_ID_CURR").agg(
            
            # bad_ratio
            mean_bad_ratio_6m=("bad_ratio_6m","mean"),
            mean_bad_ratio_12m=("bad_ratio_12m","mean"),
            mean_bad_ratio_24m=("bad_ratio_24m","mean"),
            mean_bad_ratio_all=("bad_ratio_all","mean"),

            # Loan portfolio
            total_loans=("SK_ID_BUREAU", "count"),
            active_loans=("ACTIVE_LOAN", "sum"),
            closed_loans=("CLOSED_LOAN", "sum"),

            # Exposure
            total_credit=("AMT_CREDIT_SUM", "sum"),
            total_debt=("AMT_CREDIT_SUM_DEBT", "sum"),
            total_overdue=("AMT_CREDIT_SUM_OVERDUE", "sum"),

            overdue_loans=("OVERDUE_LOAN", "sum"),

            total_prolong=("CNT_CREDIT_PROLONG", "sum"),

            # Credit history
            oldest_credit_days=("DAYS_CREDIT", "min"),

            latest_enddate=("DAYS_CREDIT_ENDDATE", "max"),

            # Delinquency severity
            worst_dpd_6m=("max_dpd_6m", "max"),
            worst_dpd_12m=("max_dpd_12m", "max"),
            worst_dpd_24m=("max_dpd_24m", "max"),
            worst_dpd_all=("max_dpd_all", "max"),

            # Delinquency frequency
            bad_months_6m=("bad_months_6m", "sum"),
            bad_months_12m=("bad_months_12m", "sum"),
            bad_months_24m=("bad_months_24m", "sum"),
            bad_months_all=("bad_months_all", "sum"),

            # Number of delinquent loans
            dpd30_loans_6m=("DPD30_6M_LOAN", "sum"),
            dpd30_loans_12m=("DPD30_12M_LOAN", "sum"),
            dpd30_loans_24m=("DPD30_24M_LOAN", "sum")

        ).reset_index()
    )

    feature["active_ratio"] = (
        feature["active_loans"] /
        feature["total_loans"]
    ).round(4)

    feature["credit_utilization"] = (
        feature["total_debt"] /
        feature["total_credit"]
    )

    feature["credit_history_years"] = (
        feature["oldest_credit_days"] / 365
    ).round(2)

    return feature

In [41]:
bureau_feature = bureau_features(bureau_enriched_new)
bureau_feature_val = bureau_features(bureau_enriched_new_val)
bureau_feature_test = bureau_features(bureau_enriched_new_test)

bureau_feature

,SK_ID_CURR,mean_bad_ratio_6m,mean_bad_ratio_12m,mean_bad_ratio_24m,mean_bad_ratio_all,total_loans,active_loans,closed_loans,total_credit,total_debt,...,bad_months_6m,bad_months_12m,bad_months_24m,bad_months_all,dpd30_loans_6m,dpd30_loans_12m,dpd30_loans_24m,active_ratio,credit_utilization,credit_history_years
0,100002,0.0,0.0,0.249206,0.255688,8,2,6,865055.565,245781.00,...,0.0,0.0,8.0,27.0,0,0,0,0.2500,0.284122,-3.94
1,100003,NaN,NaN,NaN,NaN,4,1,3,1017400.500,0.00,...,0.0,0.0,0.0,0.0,0,0,0,0.2500,0.000000,-7.08
2,100004,NaN,NaN,NaN,NaN,2,0,2,189037.800,0.00,...,0.0,0.0,0.0,0.0,0,0,0,0.0000,0.000000,-3.63
3,100007,NaN,NaN,NaN,NaN,1,0,1,146250.000,0.00,...,0.0,0.0,0.0,0.0,0,0,0,0.0000,0.000000,-3.15
4,100008,NaN,NaN,NaN,NaN,3,1,2,468445.500,240057.00,...,0.0,0.0,0.0,0.0,0,0,0,0.3333,0.512454,-3.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184416,456243,NaN,NaN,NaN,NaN,7,2,5,1787773.500,1247454.00,...,0.0,0.0,0.0,0.0,0,0,0,0.2857,0.697770,-6.46
184417,456246,NaN,NaN,NaN,NaN,3,1,2,382500.000,0.00,...,0.0,0.0,0.0,0.0,0,0,0,0.3333,0.000000,-5.87
184418,456253,0.0,0.0,0.000000,0.000000,4,2,2,3960000.000,1795833.00,...,0.0,0.0,0.0,0.0,0,0,0,0.5000,0.453493,-2.52
184419,456254,0.0,0.0,0.000000,0.000000,1,0,1,45000.000,0.00,...,0.0,0.0,0.0,0.0,0,0,0,0.0000,0.000000,-3.02
184420,456255,0.0,0.0,0.000000,0.000000,11,5,6,3801919.500,1534913.01,...,0.0,0.0,0.0,0.0,0,0,0,0.4545,0.403721,-6.40

In [42]:
bureau_feature.isnull().mean().sort_values(ascending = True)

SK_ID_CURR              0.000000
closed_loans            0.000000
active_loans            0.000000
total_loans             0.000000
overdue_loans           0.000000
total_overdue           0.000000
total_debt              0.000000
total_credit            0.000000
total_prolong           0.000000
oldest_credit_days      0.000000
active_ratio            0.000000
dpd30_loans_6m          0.000000
bad_months_12m          0.000000
bad_months_24m          0.000000
bad_months_all          0.000000
bad_months_6m           0.000000
credit_history_years    0.000000
dpd30_loans_12m         0.000000
dpd30_loans_24m         0.000000
credit_utilization      0.003790
latest_enddate          0.008654
mean_bad_ratio_all      0.651092
worst_dpd_all           0.651092
mean_bad_ratio_24m      0.655956
worst_dpd_24m           0.655956
worst_dpd_12m           0.659659
mean_bad_ratio_12m      0.659659
mean_bad_ratio_6m       0.662913
worst_dpd_6m            0.662913
dtype: float64

## Previous_application

### pos_cash_balance

POS_CASH = Point of Sale + Cash Loan

Đây là lịch sử thanh toán hàng tháng của các khoản vay trả góp tại điểm bán (mua điện thoại, tivi, laptop trả góp...) hoặc các khoản cash loan trước đây của khách hàng tại Home Credit.

previous_application.csv trả lời câu hỏi "Khách hàng đã từng xin vay gì tại Home Credit?", còn POS_CASH_balance.csv trả lời câu hỏi "Sau khi khoản vay đó được giải ngân, khách hàng đã trả nợ như thế nào theo từng tháng?"

theo dõi tình trạng của khoản vay được liên kết từ previous_application

In [43]:
pcb_train = pd.read_csv("../data/POS_CASH_balance.csv")
pcb = pcb_train[pcb_train["SK_ID_CURR"].isin(sk_id_curr_train)]

pcb_val = pcb_train[pcb_train["SK_ID_CURR"].isin(sk_id_curr_val)]
pcb_test = pcb_train[pcb_train["SK_ID_CURR"].isin(sk_id_curr_test)]



pcb

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.0,45.0,Active,0,0
1,1715348,367990,-33,36.0,35.0,Active,0,0
2,1784872,397406,-32,12.0,9.0,Active,0,0
3,1903291,269225,-35,48.0,42.0,Active,0,0
4,2341044,334279,-35,36.0,35.0,Active,0,0
...,...,...,...,...,...,...,...,...
10001352,2700641,448867,-19,6.0,0.0,Active,843,0
10001353,2448283,226558,-20,6.0,0.0,Active,843,0
10001354,1717234,141565,-19,12.0,0.0,Active,602,0
10001356,1082516,450255,-22,12.0,0.0,Active,614,0
10001357,1259607,174278,-52,16.0,0.0,Completed,0,0

In [21]:
pcb.isnull().mean()

SK_ID_PREV               0.000000
SK_ID_CURR               0.000000
MONTHS_BALANCE           0.000000
CNT_INSTALMENT           0.002607
CNT_INSTALMENT_FUTURE    0.002608
NAME_CONTRACT_STATUS     0.000000
SK_DPD                   0.000000
SK_DPD_DEF               0.000000
dtype: float64

In [22]:
pcb["NAME_CONTRACT_STATUS"].value_counts(normalize = True)

NAME_CONTRACT_STATUS
Active                   9.149876e-01
Completed                7.447819e-02
Signed                   8.724815e-03
Demand                   7.064041e-04
Returned to the store    5.460258e-04
Approved                 4.916332e-04
Amortized debt           6.359136e-05
Canceled                 1.499796e-06
XNA                      1.999728e-07
Name: proportion, dtype: float64

In [44]:
def pcb_features(df):
    temp_1 = df.copy()
    
    temp_1["BAD_MONTH"] = (temp_1["SK_DPD"] > 0).astype(int)
    
    temp_1["DPD30"] = (temp_1["SK_DPD"] > 30).astype(int)
    temp_1["DPD60"] = (temp_1["SK_DPD"] > 60).astype(int)
    temp_1["DPD90"] = (temp_1["SK_DPD"] > 90).astype(int)
    
    #-------------- all history --------------------------------
    
    feature_1 = (
    temp_1.groupby("SK_ID_CURR").agg(
        worst_pos_dpd_all=("SK_DPD", "max"),
        bad_months_all=("BAD_MONTH", "sum"),
        months_observed_all=("MONTHS_BALANCE", "count"),
        n_pos_loans=("SK_ID_PREV", "nunique")
    )
    .reset_index()
)

    feature_1["bad_ratio_all"] = (feature_1["bad_months_all"] /feature_1["months_observed_all"])

    
    
    
    # -------------- last 12 months -------------------------------
    temp_2 = temp_1[temp_1["MONTHS_BALANCE"] >= -12].copy()
    
    feature_2 = (temp_2.groupby("SK_ID_CURR").agg(
        worst_pos_dpd_12m=("SK_DPD", "max"),

            bad_months_12m=("BAD_MONTH", "sum"),

            months_observed_12m=("MONTHS_BALANCE", "count"),

            dpd30_months_12m=("DPD30", "sum"),

            dpd60_months_12m=("DPD60", "sum"),

            dpd90_months_12m=("DPD90", "sum")
    ).reset_index()
                 )
    
    feature_2["bad_ratio_12m"] = (feature_2["bad_months_12m"] /feature_2["months_observed_12m"])
    
    # =========================
    # COMPLETED LOANS
    # =========================

    completed_feat = (
        temp_1[
            temp_1["NAME_CONTRACT_STATUS"] == "Completed"
        ]
        .groupby("SK_ID_CURR")
        .agg(
            completed_loans=("SK_ID_PREV", "nunique"),

            recent_completed_month=(
                "MONTHS_BALANCE",
                "max"
            )
        )
        .reset_index()
    )
    
     # =========================
    # ACTIVE LOANS
    # =========================

    active_feat = (
        temp_1[
            temp_1["NAME_CONTRACT_STATUS"] == "Active"
        ]
        .groupby("SK_ID_CURR")
        .agg(
            active_pos_loans=("SK_ID_PREV", "nunique")
        )
        .reset_index()
    )
    
    
    # =========================
    # CURRENT BURDEN
    # Snapshot gần nhất của mỗi loan
    # =========================

    latest_snapshot = (
        temp_1.sort_values(
            ["SK_ID_PREV", "MONTHS_BALANCE"],
            ascending=[True, False]
        )
        .groupby("SK_ID_PREV")
        .head(1)
    )

    burden_feat = (
        latest_snapshot.groupby("SK_ID_CURR")
        .agg(
            total_future_instalments=(
                "CNT_INSTALMENT_FUTURE",
                "sum"
            ),

            mean_future_instalments=(
                "CNT_INSTALMENT_FUTURE",
                "mean"
            ),

            max_future_instalments=(
                "CNT_INSTALMENT_FUTURE",
                "max"
            )
        )
        .reset_index()
    )
    
    pos_features = (
        feature_1
        .merge(feature_2,
               on="SK_ID_CURR",
               how="left")
        .merge(completed_feat,
               on="SK_ID_CURR",
               how="left")
        .merge(active_feat,
               on="SK_ID_CURR",
               how="left")
        .merge(burden_feat,
               on="SK_ID_CURR",
               how="left")
    )

    return pos_features

In [45]:
pcb_feature = pcb_features(pcb)

pcb_feature_val = pcb_features(pcb_val)

pcb_feature_test = pcb_features(pcb_test)



pcb_feature.head()

,SK_ID_CURR,worst_pos_dpd_all,bad_months_all,months_observed_all,n_pos_loans,bad_ratio_all,worst_pos_dpd_12m,bad_months_12m,months_observed_12m,dpd30_months_12m,dpd60_months_12m,dpd90_months_12m,bad_ratio_12m,completed_loans,recent_completed_month,active_pos_loans,total_future_instalments,mean_future_instalments,max_future_instalments
0,100002,0,0,19,1,0.000000,0.0,0.0,12.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,6.0,6.000000,6.0
1,100003,0,0,28,3,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,-18.0,3.0,1.0,0.333333,1.0
2,100004,0,0,4,1,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,-24.0,1.0,0.0,0.000000,0.0
3,100007,0,0,66,5,0.000000,0.0,0.0,14.0,0.0,0.0,0.0,0.0,3.0,-11.0,5.0,14.0,2.800000,13.0
4,100008,1294,43,83,4,0.518072,0.0,0.0,11.0,0.0,0.0,0.0,0.0,4.0,-2.0,4.0,0.0,0.000000,0.0

In [25]:
pcb_feature.isnull().mean()

SK_ID_CURR                  0.000000
worst_pos_dpd_all           0.000000
bad_months_all              0.000000
months_observed_all         0.000000
n_pos_loans                 0.000000
bad_ratio_all               0.000000
worst_pos_dpd_12m           0.287669
bad_months_12m              0.287669
months_observed_12m         0.287669
dpd30_months_12m            0.287669
dpd60_months_12m            0.287669
dpd90_months_12m            0.287669
bad_ratio_12m               0.287669
completed_loans             0.109746
recent_completed_month      0.109746
active_pos_loans            0.000646
total_future_instalments    0.000000
mean_future_instalments     0.000083
max_future_instalments      0.000083
dtype: float64

### credit card balance
Bảng này chứa lịch sử sử dụng thẻ tín dụng hàng tháng của khách hàng tại Home Credit trước khi họ nộp đơn vay hiện tại.

Không phải mọi đơn trong previous_application.csv đều là khoản vay trả góp; một số đơn là đăng ký sản phẩm thẻ tín dụng (revolving credit). Khi khách hàng được cấp thẻ tín dụng, Home Credit không theo dõi bằng các kỳ trả góp cố định mà theo dõi tài khoản thẻ theo từng kỳ sao kê hàng tháng. credit_card_balance.csv ghi nhận toàn bộ hoạt động này: dư nợ cuối kỳ, hạn mức tín dụng, số tiền đã chi tiêu, số tiền rút tiền mặt, số tiền khách hàng thanh toán và số ngày quá hạn nếu có.

In [46]:
ccb_train = pd.read_csv("../data/credit_card_balance.csv")
ccb = ccb_train[ccb_train["SK_ID_CURR"].isin(sk_id_curr_train)]

ccb_val = ccb_train[ccb_train["SK_ID_CURR"].isin(sk_id_curr_val)]
ccb_test = ccb_train[ccb_train["SK_ID_CURR"].isin(sk_id_curr_test)]


ccb

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
1,2582071,363914,-1,63975.555,45000,2250.0,2250.000,0.0,0.000,2250.00,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.000,0.0,0.000,11795.76,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.000,0.0,11547.000,22924.89,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0
8,2181852,367360,-4,291543.075,292500,90000.0,289339.425,0.0,199339.425,130.50,...,286831.575,286831.575,3.0,8,0.0,5.0,3.0,Active,0,0
11,2740914,340339,-1,131669.145,225000,10800.0,10800.000,0.0,0.000,6000.48,...,127891.935,127891.935,2.0,2,0.0,0.0,6.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840303,1307188,385981,-9,0.000,0,NaN,0.000,NaN,NaN,0.00,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3840304,1301378,303373,-15,0.000,0,0.0,0.000,0.0,0.000,0.00,...,0.000,0.000,0.0,0,0.0,0.0,60.0,Active,0,0
3840306,1410474,255737,-13,0.000,180000,NaN,0.000,NaN,NaN,0.00,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3840308,1714892,347207,-9,0.000,45000,0.0,0.000,0.0,0.000,0.00,...,0.000,0.000,0.0,0,0.0,0.0,23.0,Active,0,0
3840311,2411345,236760,-10,0.000,157500,0.0,0.000,0.0,0.000,0.00,...,0.000,0.000,0.0,0,0.0,0.0,21.0,Completed,0,0

In [27]:
ccb.sort_values(["SK_ID_CURR","MONTHS_BALANCE"], ascending = [True,False]).head(13)

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
584804,1489396,100006,-1,0.0,270000,NaN,0.0,NaN,NaN,0.0,...,0.0,0.0,NaN,0,NaN,NaN,0.0,Active,0,0
520387,1489396,100006,-2,0.0,270000,NaN,0.0,NaN,NaN,0.0,...,0.0,0.0,NaN,0,NaN,NaN,0.0,Active,0,0
1347528,1489396,100006,-3,0.0,270000,NaN,0.0,NaN,NaN,0.0,...,0.0,0.0,NaN,0,NaN,NaN,0.0,Active,0,0
1399895,1489396,100006,-4,0.0,270000,NaN,0.0,NaN,NaN,0.0,...,0.0,0.0,NaN,0,NaN,NaN,0.0,Active,0,0
655566,1489396,100006,-5,0.0,270000,NaN,0.0,NaN,NaN,0.0,...,0.0,0.0,NaN,0,NaN,NaN,0.0,Active,0,0
1636141,1489396,100006,-6,0.0,270000,NaN,0.0,NaN,NaN,0.0,...,0.0,0.0,NaN,0,NaN,NaN,0.0,Active,0,0
2739019,1843384,100011,-2,0.0,90000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,33.0,Active,0,0
3496910,1843384,100011,-3,0.0,90000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,33.0,Active,0,0
51047,1843384,100011,-4,0.0,90000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,33.0,Active,0,0
2674883,1843384,100011,-5,0.0,90000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,33.0,Active,0,0
131693,1843384,100011,-6,0.0,90000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,33.0,Active,0,0
3637571,1843384,100011,-7,0.0,90000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,33.0,Active,0,0
2684587,1843384,100011,-8,0.0,90000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,33.0,Active,0,0

In [47]:
def ccb_features(df):
    temp = df.copy()
    
    # số dư nợ so với hạn mức tín dụng của thẻ
    temp["UTILIZATION"] = np.where(temp["AMT_CREDIT_LIMIT_ACTUAL"] > 0, temp["AMT_BALANCE"] / temp["AMT_CREDIT_LIMIT_ACTUAL"], np.nan) 
    
    cc = (temp.groupby("SK_ID_CURR").agg(
        avg_util_all=("UTILIZATION", "mean"),

        total_drawings=("AMT_DRAWINGS_CURRENT", "sum"),
        avg_drawings=("AMT_DRAWINGS_CURRENT", "mean"),

        max_dpd_cc=("SK_DPD", "max"),
        avg_dpd_cc=("SK_DPD", "mean"),

        months_observed_cc=("MONTHS_BALANCE", "count"),

        num_cc_accounts=("SK_ID_PREV", "nunique")
    ).reset_index())
    
    # ----------- Recent 6 Months ------------------------------
    recent_6m = temp[temp["MONTHS_BALANCE"] >= -5]
    
    cc_recent_6m = (temp.groupby("SK_ID_CURR").agg(
        avg_util_6m = ("UTILIZATION", "mean"),
        mã_util_6m = ("UTILIZATION","max")
    ).reset_index())
    
    # ----------- UTILIZATION trend ---------------------------- avg util (0,-1,-2) - avg util (-3,-4,-5)
    recent_3m = (temp[temp["MONTHS_BALANCE"] >= -2].groupby("SK_ID_CURR")["UTILIZATION"].mean())

    previous_3m = (temp[(temp["MONTHS_BALANCE"] <= -3)& (temp["MONTHS_BALANCE"] >= -5)].groupby("SK_ID_CURR")["UTILIZATION"].mean())

    cc_trend = ( pd.concat([recent_3m.rename("recent_util"),previous_3m.rename("previous_util")], axis=1).reset_index())

    cc_trend["util_trend"] = (cc_trend["recent_util"]- cc_trend["previous_util"])

    cc_trend = cc_trend[["SK_ID_CURR", "util_trend"]]
    
    # ----------- lastest statement ----------------------------
    lastest = (temp.sort_values(["SK_ID_CURR", "MONTHS_BALANCE"], ascending = [True, False]).groupby("SK_ID_CURR").first().reset_index())
    
    lastest["payment_ratio_last"] = np.where(lastest["AMT_BALANCE"]> 0, lastest["AMT_PAYMENT_TOTAL_CURRENT"] / lastest["AMT_BALANCE"], np.nan)
    
    cc_lastest = lastest[["SK_ID_CURR", "payment_ratio_last"]]
    
    cc_feature = (cc.merge(cc_recent_6m, on = "SK_ID_CURR", how = 'left')
                  .merge(cc_trend, on = "SK_ID_CURR", how = 'left')
                  .merge(cc_lastest, on ="SK_ID_CURR", how = 'left'))
    
    return cc_feature

In [48]:
ccb_feature = ccb_features(ccb)

ccb_feature_val = ccb_features(ccb_val)
ccb_feature_test = ccb_features(ccb_test)


ccb_feature.head()

,SK_ID_CURR,avg_util_all,total_drawings,avg_drawings,max_dpd_cc,avg_dpd_cc,months_observed_cc,num_cc_accounts,avg_util_6m,mã_util_6m,util_trend,payment_ratio_last
0,100021,0.000000,0.000,0.000000,0,0.0,17,1,0.000000,0.000000,0.000000,NaN
1,100036,0.000000,0.000,0.000000,0,0.0,12,1,0.000000,0.000000,0.000000,NaN
2,100043,0.487889,491864.085,14904.972273,0,0.0,33,1,0.487889,1.019559,0.000000,NaN
3,100047,0.000000,0.000,0.000000,0,0.0,36,1,0.000000,0.000000,NaN,NaN
4,100048,0.265825,496296.000,16009.548387,0,0.0,31,1,0.265825,0.942280,0.061296,83.306632

### Installments Payments

lưu lịch sử thanh toán thực tế của từng kỳ trả góp đối với các khoản vay trước đây của khách hàng tại Home Credit.

Nếu POS_CASH_balance.csv cho biết trạng thái khoản vay theo từng tháng, thì installments_payments.csv đi sâu hơn đến từng kỳ thanh toán. Sau khi một khoản vay trong previous_application.csv được giải ngân, hệ thống sẽ tạo lịch trả nợ (repayment schedule). Mỗi kỳ sẽ có một ngày đến hạn và một số tiền phải trả. installments_payments.csv lưu lại khách hàng đã trả bao nhiêu tiền, vào ngày nào, có trả đúng hạn hay không, trả thiếu hay trả dư cho từng kỳ. Nói cách khác, bảng này là lịch sử giao dịch thanh toán thực tế của khoản vay

In [49]:
ip_train = pd.read_csv("../data/installments_payments.csv")
ip = ip_train[ip_train["SK_ID_CURR"].isin(sk_id_curr_train)]

ip_val = ip_train[ip_train["SK_ID_CURR"].isin(sk_id_curr_val)]
ip_test = ip_train[ip_train["SK_ID_CURR"].isin(sk_id_curr_test)]


ip

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
0,1054186,161674,1.0,6,-1180.0,-1187.0,6948.360,6948.360
1,1330831,151639,0.0,34,-2156.0,-2156.0,1716.525,1716.525
2,2085231,193053,2.0,1,-63.0,-63.0,25425.000,25425.000
3,2452527,199697,1.0,3,-2418.0,-2426.0,24350.130,24350.130
7,1818599,111420,2.0,4,-968.0,-994.0,17862.165,17862.165
...,...,...,...,...,...,...,...,...
13605391,1499195,418486,6.0,32,-112.0,NaN,48635.595,NaN
13605393,1285736,434069,0.0,73,-853.0,NaN,67.500,NaN
13605395,1499195,418486,6.0,2,-1012.0,NaN,48635.595,NaN
13605396,2186857,428057,0.0,66,-1624.0,NaN,67.500,NaN
13605397,1310347,414406,0.0,47,-1539.0,NaN,67.500,NaN

In [31]:
ip.sort_values(["SK_ID_CURR","NUM_INSTALMENT_NUMBER"], ascending= [True,True]).head(10)

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
1478621,1369693,100001,1.0,1,-1709.0,-1715.0,3951.000,3951.000
1761012,1851984,100001,1.0,2,-2916.0,-2916.0,3982.050,3982.050
2568722,1369693,100001,1.0,2,-1679.0,-1715.0,3951.000,3951.000
3458712,1369693,100001,1.0,3,-1649.0,-1660.0,3951.000,3951.000
3774071,1851984,100001,1.0,3,-2886.0,-2875.0,3982.050,3982.050
2624024,1369693,100001,2.0,4,-1619.0,-1628.0,17397.900,17397.900
3435373,1851984,100001,1.0,4,-2856.0,-2856.0,3980.925,3980.925
2144879,1038818,100002,1.0,1,-565.0,-587.0,9251.775,9251.775
2163032,1038818,100002,1.0,2,-535.0,-562.0,9251.775,9251.775
1675768,1038818,100002,1.0,3,-505.0,-529.0,9251.775,9251.775

In [32]:
ip.isna().mean()

SK_ID_PREV                0.000000
SK_ID_CURR                0.000000
NUM_INSTALMENT_VERSION    0.000000
NUM_INSTALMENT_NUMBER     0.000000
DAYS_INSTALMENT           0.000000
DAYS_ENTRY_PAYMENT        0.000214
AMT_INSTALMENT            0.000000
AMT_PAYMENT               0.000214
dtype: float64

In [33]:
ip.describe()

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
count,1.360540e+07,1.360540e+07,1.360540e+07,1.360540e+07,1.360540e+07,1.360250e+07,1.360540e+07,1.360250e+07
mean,1.903365e+06,2.784449e+05,8.566373e-01,1.887090e+01,-1.042270e+03,-1.051114e+03,1.705091e+04,1.723822e+04
std,5.362029e+05,1.027183e+05,1.035216e+00,2.666407e+01,8.009463e+02,8.005859e+02,5.057025e+04,5.473578e+04
min,1.000001e+06,1.000010e+05,0.000000e+00,1.000000e+00,-2.922000e+03,-4.921000e+03,0.000000e+00,0.000000e+00
25%,1.434191e+06,1.896390e+05,0.000000e+00,4.000000e+00,-1.654000e+03,-1.662000e+03,4.226085e+03,3.398265e+03
50%,1.896520e+06,2.786850e+05,1.000000e+00,8.000000e+00,-8.180000e+02,-8.270000e+02,8.884080e+03,8.125515e+03
75%,2.369094e+06,3.675300e+05,1.000000e+00,1.900000e+01,-3.610000e+02,-3.700000e+02,1.671021e+04,1.610842e+04
max,2.843499e+06,4.562550e+05,1.780000e+02,2.770000e+02,-1.000000e+00,-1.000000e+00,3.771488e+06,3.771488e+06

In [34]:
ip.shape

(13605401, 8)

In [50]:
def ip_features(df):
    temp = df.copy()
    
    # --------------- PAYMENT RATIO ---------------
    temp['PAYMENT_RATIO'] = np.where(temp["AMT_INSTALMENT"] > 0, temp["AMT_PAYMENT"] / temp['AMT_INSTALMENT'], np.nan)
    
    # --------------- UNDER PAYMENT ---------------
    temp["UNPAID"] = (temp["PAYMENT_RATIO"] < 0.95).astype(int)
    
    #---------------- Days late ---------------------------
    # ------------ positive: not late, negative: late------
    temp['DAYS_LATE'] = temp["DAYS_ENTRY_PAYMENT"] - temp['DAYS_INSTALMENT']
    temp["LATE_PAY"] = (temp["DAYS_LATE"] > 0).astype(int)
    temp["LATE_7_DAYS"] = (temp["DAYS_LATE"] > 7).astype(int)
    
    # -------------- agg history ----------------------------
    feature_history = (temp.groupby("SK_ID_CURR").agg(
        avg_payment_ratio = ("PAYMENT_RATIO", "mean"),
        min_payment_ratio = ("PAYMENT_RATIO", "min"),
        
        underpaid_count = ("UNPAID", "sum"),
        
        avg_day_late = ("DAYS_LATE","mean"),
        max_day_late = ("DAYS_LATE","max"),
        
        late_count = ("LATE_PAY", "sum"),
        late_count_7 = ("LATE_7_DAYS", "sum"),
        
        total_installment = ("SK_ID_PREV", "count")
        
    ).reset_index())
    
    # -------------- last 12 months ---------------------
    last_12_months = temp[temp["DAYS_INSTALMENT"] >= - 365]
    feature_last_12 = (last_12_months.groupby("SK_ID_CURR").agg(
        avg_payment_12m = ("PAYMENT_RATIO", "mean"),
        
        underpaid_count_12m = ("UNPAID", "sum"),
        
        avg_day_late_12m = ("DAYS_LATE","mean"),
        
        installment_12m = ("SK_ID_PREV","count" ) 
    ).reset_index()) 
    
    # ------------- Late payment rate -----------------
    feature_history["late_payment_rate"] = feature_history['late_count'] / feature_history["total_installment"]
    
    feature = (feature_history.merge(feature_last_12, on = "SK_ID_CURR", how = "left"))
    
    return feature

In [51]:
ip_feature = ip_features(ip)

ip_feature_val = ip_features(ip_val)
ip_feature_test = ip_features(ip_test)



ip_feature.head()

,SK_ID_CURR,avg_payment_ratio,min_payment_ratio,underpaid_count,avg_day_late,max_day_late,late_count,late_count_7,total_installment,late_payment_rate,avg_payment_12m,underpaid_count_12m,avg_day_late_12m,installment_12m
0,100002,1.000000,1.000000,0,-20.421053,-12.0,0,0,19,0.000000,1.0,0.0,-17.583333,12.0
1,100003,1.000000,1.000000,0,-7.160000,-1.0,0,0,25,0.000000,NaN,NaN,NaN,NaN
2,100004,1.000000,1.000000,0,-7.666667,-3.0,0,0,3,0.000000,NaN,NaN,NaN,NaN
3,100007,0.954545,0.000050,3,-3.636364,12.0,16,2,66,0.242424,1.0,0.0,-3.615385,13.0
4,100008,0.971429,0.018952,1,26.114286,1317.0,1,1,35,0.028571,1.0,0.0,-11.000000,10.0

In [37]:
ip_feature.isna().mean()

SK_ID_CURR             0.000000
avg_payment_ratio      0.000035
min_payment_ratio      0.000035
underpaid_count        0.000000
avg_day_late           0.000027
max_day_late           0.000027
late_count             0.000000
late_count_7           0.000000
total_installment      0.000000
late_payment_rate      0.000000
avg_payment_12m        0.255781
underpaid_count_12m    0.255681
avg_day_late_12m       0.255781
installment_12m        0.255681
dtype: float64

### PREVIOUS APPLICAITON

previous_application.csv lưu thông tin về mọi lần khách hàng từng nộp đơn xin một sản phẩm tín dụng tại Home Credit, bất kể đơn đó được duyệt, bị từ chối, bị hủy hay khách hàng không sử dụng khoản vay sau khi được duyệt.

In [52]:
pre_app_train = pd.read_csv("../data/previous_application.csv")
pre_app = pre_app_train[pre_app_train["SK_ID_CURR"].isin(sk_id_curr_train)]
pre_app_val = pre_app_train[pre_app_train["SK_ID_CURR"].isin(sk_id_curr_val)]
pre_app_test = pre_app_train[pre_app_train["SK_ID_CURR"].isin(sk_id_curr_test)]


pre_app

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1670207,1662353,443544,Cash loans,12607.875,112500.0,112500.0,0.0,112500.0,MONDAY,10,...,XNA,12.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN
1670208,1556789,209732,Cash loans,22299.390,315000.0,436216.5,NaN,315000.0,THURSDAY,17,...,XNA,36.0,middle,Cash X-Sell: middle,365243.0,-1249.0,-199.0,-919.0,-912.0,1.0
1670211,2659632,249544,Consumer loans,11520.855,105237.0,102523.5,10525.5,105237.0,MONDAY,12,...,Consumer electronics,10.0,low_normal,POS household with interest,365243.0,-1457.0,-1187.0,-1187.0,-1181.0,0.0
1670212,2785582,400317,Cash loans,18821.520,180000.0,191880.0,NaN,180000.0,WEDNESDAY,9,...,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-1155.0,-825.0,-825.0,-817.0,1.0
1670213,2418762,261212,Cash loans,16431.300,360000.0,360000.0,NaN,360000.0,SUNDAY,10,...,XNA,48.0,middle,Cash X-Sell: middle,365243.0,-1163.0,247.0,-443.0,-423.0,0.0

In [39]:
pre_app.isna().mean().round(2)

SK_ID_PREV                     0.00
SK_ID_CURR                     0.00
NAME_CONTRACT_TYPE             0.00
AMT_ANNUITY                    0.22
AMT_APPLICATION                0.00
AMT_CREDIT                     0.00
AMT_DOWN_PAYMENT               0.54
AMT_GOODS_PRICE                0.23
WEEKDAY_APPR_PROCESS_START     0.00
HOUR_APPR_PROCESS_START        0.00
FLAG_LAST_APPL_PER_CONTRACT    0.00
NFLAG_LAST_APPL_IN_DAY         0.00
RATE_DOWN_PAYMENT              0.54
RATE_INTEREST_PRIMARY          1.00
RATE_INTEREST_PRIVILEGED       1.00
NAME_CASH_LOAN_PURPOSE         0.00
NAME_CONTRACT_STATUS           0.00
DAYS_DECISION                  0.00
NAME_PAYMENT_TYPE              0.00
CODE_REJECT_REASON             0.00
NAME_TYPE_SUITE                0.49
NAME_CLIENT_TYPE               0.00
NAME_GOODS_CATEGORY            0.00
NAME_PORTFOLIO                 0.00
NAME_PRODUCT_TYPE              0.00
CHANNEL_TYPE                   0.00
SELLERPLACE_AREA               0.00
NAME_SELLER_INDUSTRY           0.00
CNT_PAYMENT                    0.22
NAME_YIELD_GROUP               0.00
PRODUCT_COMBINATION            0.00
DAYS_FIRST_DRAWING             0.40
DAYS_FIRST_DUE                 0.40
DAYS_LAST_DUE_1ST_VERSION      0.40
DAYS_LAST_DUE                  0.40
DAYS_TERMINATION               0.40
NFLAG_INSURED_ON_APPROVAL      0.40
dtype: float64

In [53]:
def previous_application_features(df):

    temp = df.copy()

    # -----------------Credit / Application Ratio -----------------------
    temp["CREDIT_APP_RATIO"] = np.where(
        temp["AMT_APPLICATION"] > 0,
        temp["AMT_CREDIT"] / temp["AMT_APPLICATION"],
        np.nan
    )

    #------------------ Status Flags ---------------------------
    temp["APPROVED"] = (
        temp["NAME_CONTRACT_STATUS"] == "Approved"
    ).astype(int)

    temp["REFUSED"] = (
        temp["NAME_CONTRACT_STATUS"] == "Refused"
    ).astype(int)

    temp["CANCELED"] = (
        temp["NAME_CONTRACT_STATUS"] == "Canceled"
    ).astype(int)

    temp["RECENT_12M"] = (
        temp["DAYS_DECISION"] >= -365
    ).astype(int)

    temp["INSURED"] = (
        temp["NFLAG_INSURED_ON_APPROVAL"] == 1
    ).astype(int)

    #-------------- Basic Aggregate ------------------------------
    
    prev_basic = (
        temp.groupby("SK_ID_CURR")
        .agg(
            total_applications=("SK_ID_PREV", "count"),

            approved_count=("APPROVED", "sum"),
            refused_count=("REFUSED", "sum"),
            canceled_count=("CANCELED", "sum"),

            applications_12m=("RECENT_12M", "sum"),

            insured_count=("INSURED", "sum")
        )
        .reset_index()
    )

    # --------------------------- Approval Rate------------------------
    prev_basic["approval_rate"] = (
        prev_basic["approved_count"]
        / prev_basic["total_applications"]
    )

    # --------------------------- Approved Loans Only -----------------
    approved = temp[
        temp["NAME_CONTRACT_STATUS"] == "Approved"
    ]

    prev_approved = (
        approved.groupby("SK_ID_CURR")
        .agg(
            avg_application_amount=("AMT_APPLICATION", "mean"),

            avg_credit_application_ratio=(
                "CREDIT_APP_RATIO",
                "mean"
            )
        )
        .reset_index()
    )

    # --------------------------- Latest Application ----------------------------
    # --------------------------- max(DAYS_DECISION) = gần observation point nhất
    latest_application = (
        temp.sort_values(
            ["SK_ID_CURR", "DAYS_DECISION"],
            ascending=[True, False]
        )
        .groupby("SK_ID_CURR")
        .first()
        .reset_index()
    )

    latest_application = latest_application[
        [
            "SK_ID_CURR",
            "AMT_CREDIT",
            "AMT_ANNUITY",
            "DAYS_DECISION"
        ]
    ].rename(
        columns={
            "AMT_CREDIT": "latest_credit_amount",
            "AMT_ANNUITY": "latest_annuity",
            "DAYS_DECISION": "latest_days_decision"
        }
    )
    
    
    # ----------------------- Days Since Latest Application -------------------
    latest_application["days_since_last_application"] = (
        -latest_application["latest_days_decision"]
    )

    
    # ---------------------- Merge ---------------------------------------------
    prev_features = (
        prev_basic
        .merge(
            prev_approved,
            on="SK_ID_CURR",
            how="left"
        )
        .merge(
            latest_application,
            on="SK_ID_CURR",
            how="left"
        )
    )

    return prev_features

In [54]:
pre_app_feature = previous_application_features(pre_app)
pre_app_feature_val = previous_application_features(pre_app_val)
pre_app_feature_test = previous_application_features(pre_app_test)


pre_app_feature.head()

,SK_ID_CURR,total_applications,approved_count,refused_count,canceled_count,applications_12m,insured_count,approval_rate,avg_application_amount,avg_credit_application_ratio,latest_credit_amount,latest_annuity,latest_days_decision,days_since_last_application
0,100002,1,1,0,0,0,0,1.0,179055.00,1.000000,179055.0,9251.775,-606,606
1,100003,3,3,0,0,0,2,1.0,435436.50,1.057664,1035882.0,98356.995,-746,746
2,100004,1,1,0,0,0,0,1.0,24282.00,0.828021,20106.0,5357.250,-815,815
3,100007,6,6,0,0,0,3,1.0,150530.25,1.046356,274288.5,16037.640,-374,374
4,100008,5,4,0,1,1,1,0.8,194627.25,0.978569,0.0,17885.835,-82,82

In [42]:
pre_app_feature.isna().mean()

SK_ID_CURR                      0.000000
total_applications              0.000000
approved_count                  0.000000
refused_count                   0.000000
canceled_count                  0.000000
applications_12m                0.000000
insured_count                   0.000000
approval_rate                   0.000000
avg_application_amount          0.003420
avg_credit_application_ratio    0.006726
latest_credit_amount            0.000000
latest_annuity                  0.001417
latest_days_decision            0.000000
days_since_last_application     0.000000
dtype: float64

## Merge

In [66]:
all_feature_train = (train_feature.merge(bureau_feature,on = "SK_ID_CURR", how = "left")
                     .merge(pcb_feature,on="SK_ID_CURR",how = "left")
                     .merge(ccb_feature,on = "SK_ID_CURR",how = "left")
                     .merge(ip_feature,on = "SK_ID_CURR",how = "left")
                     .merge(pre_app_feature,on = "SK_ID_CURR",how="left"))
all_feature_train = (all_feature_train.sort_values('SK_ID_CURR')).reset_index(drop= True)
all_feature_train.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,canceled_count,applications_12m,insured_count,approval_rate,avg_application_amount,avg_credit_application_ratio,latest_credit_amount,latest_annuity,latest_days_decision,days_since_last_application
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0.0,0.0,0.0,1.0,179055.00,1.000000,179055.0,9251.775,-606.0,606.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0.0,0.0,2.0,1.0,435436.50,1.057664,1035882.0,98356.995,-746.0,746.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0.0,0.0,0.0,1.0,24282.00,0.828021,20106.0,5357.250,-815.0,815.0
3,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0.0,0.0,3.0,1.0,150530.25,1.046356,274288.5,16037.640,-374.0,374.0
4,100008,0,Cash loans,M,N,Y,0,99000.0,490495.5,27517.5,...,1.0,1.0,1.0,0.8,194627.25,0.978569,0.0,17885.835,-82.0,82.0

In [67]:
all_feature_val = (validation_feature.merge(bureau_feature_val,on = "SK_ID_CURR", how = "left")
                     .merge(pcb_feature_val,on="SK_ID_CURR",how = "left")
                     .merge(ccb_feature_val,on = "SK_ID_CURR",how = "left")
                     .merge(ip_feature_val,on = "SK_ID_CURR",how = "left")
                     .merge(pre_app_feature_val,on = "SK_ID_CURR",how="left"))
all_feature_val = all_feature_val.sort_values('SK_ID_CURR').reset_index(drop= True)
all_feature_val.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,canceled_count,applications_12m,insured_count,approval_rate,avg_application_amount,avg_credit_application_ratio,latest_credit_amount,latest_annuity,latest_days_decision,days_since_last_application
0,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,3.0,7.0,0.0,0.555556,352265.868000,0.951861,675000.000,24246.000,-181.0,181.0
1,100009,0,Cash loans,F,Y,Y,1,171000.0,1560726.0,41301.0,...,0.0,3.0,0.0,1.000000,76741.714286,0.916226,88632.000,10418.670,-74.0,74.0
2,100018,0,Cash loans,F,N,Y,0,189000.0,773680.5,32778.0,...,0.0,2.0,0.0,1.000000,298363.466250,1.014609,36805.365,4180.365,-188.0,188.0
3,100023,0,Cash loans,F,N,Y,1,90000.0,544491.0,17563.5,...,0.0,2.0,2.0,1.000000,98746.875000,1.080951,239242.500,16822.440,-262.0,262.0
4,100024,0,Revolving loans,M,Y,Y,0,135000.0,427500.0,21375.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
all_feature_test = (test_feature.merge(bureau_feature_test,on = "SK_ID_CURR", how = "left")
                     .merge(pcb_feature_test,on="SK_ID_CURR",how = "left")
                     .merge(ccb_feature_test,on = "SK_ID_CURR",how = "left")
                     .merge(ip_feature_test,on = "SK_ID_CURR",how = "left")
                     .merge(pre_app_feature_test,on = "SK_ID_CURR",how="left"))
all_feature_test = all_feature_test.sort_values('SK_ID_CURR').reset_index(drop = True)
all_feature_test.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,canceled_count,applications_12m,insured_count,approval_rate,avg_application_amount,avg_credit_application_ratio,latest_credit_amount,latest_annuity,latest_days_decision,days_since_last_application
0,100011,0,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,...,0.0,0.0,2.0,0.75,270310.50,1.037438,0.0,31295.250,-1162.0,1162.0
1,100014,0,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,...,0.0,1.0,0.0,1.00,96536.25,1.052801,73800.0,14045.625,-102.0,102.0
2,100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,...,0.0,0.0,1.0,1.00,68850.00,0.974248,67077.0,7666.920,-2396.0,2396.0
3,100020,0,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,...,0.0,1.0,0.0,1.00,39206.25,1.066006,35086.5,5729.265,-243.0,243.0
4,100022,0,Revolving loans,F,N,Y,0,112500.000,157500.0,7875.0,...,0.0,1.0,1.0,1.00,89091.00,1.158400,103203.0,6765.975,-239.0,239.0

In [69]:
all_feature_train.to_csv(
    "all_feature_train.csv",
    index=False,
    encoding="utf-8-sig"
)


all_feature_val.to_csv(
    "all_feature_val.csv",
    index=False,
    encoding="utf-8-sig"
)

all_feature_test.to_csv(
    "all_feature_test.csv",
    index=False,
    encoding="utf-8-sig"
)

In [70]:
print(f"Train null: {X_train.isnull().sum().sum()}")
print(f"Val null: {X_val.isnull().sum().sum()}")
print(f"Test null: {X_test.isnull().sum().sum()}")

Train null: 6401365
Val null: 1373702
Test null: 1377398